# Jekyll! config

# Site settings
title: BTC Fork Club

# Build settings
markdown: kramdown

# Sass style
sass:
  style: compressed

repository: agustinf/btcfork
# Site theme
#theme: jekyll-theme-minimal

theme: jekyll-theme-slate